### ISSUE TITLE
Add an additional prompt after the tests have been generated

### ISSUE THREAD

**Issue by dissto** [CodeWithDennis/filament-resource-tests#150]
Ask the user if they want to run the generated tests

> vendor/bin/pest --group="filament-tests"

It should be opt-out'able

> `php artisan make:filament-test --dontRun` (or something similar)

**Comment by CodeWithDennis** [comment]
This might help sometimes, but it could also be really annoying. You might just want to make a couple of tests, but it keeps asking you run them. And having to specify not to ask again feels a bit weird.

**Comment by CodeWithDennis** [comment]
> Optionally could make it opt-in `php artisan make:filament-test --run`

Sounds like a better option yes.
